//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-558
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.11.17 at 04:20:50 PM EST
//

package com.blumeglobal.currencyexchange.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;

/**
 * Java class for CurrencyRateTypeType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CurrencyRateTypeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CurrencyRateType" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="currencyRateTypeId" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="typeCode" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="name" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="metaData" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="updatedBy" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="updatedOn" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}dateTime">
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="createdBy" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="createdOn" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}dateTime">
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "CurrencyRateTypeType",
    propOrder = {"currencyRateType"})
public class CurrencyRateTypeType {

  @XmlElement(name = "CurrencyRateType", nillable = true)
  protected List<CurrencyRateTypeType.CurrencyRateType> currencyRateType;

  /**
   * Gets the value of the currencyRateType property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the currencyRateType property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getCurrencyRateType().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link
   * CurrencyRateTypeType.CurrencyRateType }
   */
  public List<CurrencyRateTypeType.CurrencyRateType> getCurrencyRateType() {
    if (currencyRateType == null) {
      currencyRateType = new ArrayList<CurrencyRateTypeType.CurrencyRateType>();
    }
    return this.currencyRateType;
  }

  /**
   * Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="currencyRateTypeId" minOccurs="0">
   *           &lt;simpleType>
   *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
   *             &lt;/restriction>
   *           &lt;/simpleType>
   *         &lt;/element>
   *         &lt;element name="typeCode" minOccurs="0">
   *           &lt;simpleType>
   *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
   *             &lt;/restriction>
   *           &lt;/simpleType>
   *         &lt;/element>
   *         &lt;element name="name" minOccurs="0">
   *           &lt;simpleType>
   *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
   *             &lt;/restriction>
   *           &lt;/simpleType>
   *         &lt;/element>
   *         &lt;element name="metaData" minOccurs="0">
   *           &lt;complexType>
   *             &lt;complexContent>
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                 &lt;sequence>
   *                   &lt;element name="updatedBy" minOccurs="0">
   *                     &lt;simpleType>
   *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
   *                       &lt;/restriction>
   *                     &lt;/simpleType>
   *                   &lt;/element>
   *                   &lt;element name="updatedOn" minOccurs="0">
   *                     &lt;simpleType>
   *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}dateTime">
   *                       &lt;/restriction>
   *                     &lt;/simpleType>
   *                   &lt;/element>
   *                   &lt;element name="createdBy" minOccurs="0">
   *                     &lt;simpleType>
   *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
   *                       &lt;/restriction>
   *                     &lt;/simpleType>
   *                   &lt;/element>
   *                   &lt;element name="createdOn" minOccurs="0">
   *                     &lt;simpleType>
   *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}dateTime">
   *                       &lt;/restriction>
   *                     &lt;/simpleType>
   *                   &lt;/element>
   *                 &lt;/sequence>
   *               &lt;/restriction>
   *             &lt;/complexContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(
      name = "",
      propOrder = {"currencyRateTypeId", "typeCode", "name", "metaData"})
  public static class CurrencyRateType {

    protected String currencyRateTypeId;

    @XmlElementRef(name = "typeCode", type = JAXBElement.class)
    protected JAXBElement<String> typeCode;

    @XmlElementRef(name = "name", type = JAXBElement.class)
    protected JAXBElement<String> name;

    @XmlElementRef(name = "metaData", type = JAXBElement.class)
    protected JAXBElement<CurrencyRateTypeType.CurrencyRateType.MetaData> metaData;

    /**
     * Gets the value of the currencyRateTypeId property.
     *
     * @return possible object is {@link String }
     */
    public String getCurrencyRateTypeId() {
      return currencyRateTypeId;
    }

    /**
     * Sets the value of the currencyRateTypeId property.
     *
     * @param value allowed object is {@link String }
     */
    public void setCurrencyRateTypeId(String value) {
      this.currencyRateTypeId = value;
    }

    /**
     * Gets the value of the typeCode property.
     *
     * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getTypeCode() {
      return typeCode;
    }

    /**
     * Sets the value of the typeCode property.
     *
     * @param value allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setTypeCode(JAXBElement<String> value) {
      this.typeCode = ((JAXBElement<String>) value);
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getName() {
      return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setName(JAXBElement<String> value) {
      this.name = ((JAXBElement<String>) value);
    }

    /**
     * Gets the value of the metaData property.
     *
     * @return possible object is {@link JAXBElement }{@code <}{@link
     *     CurrencyRateTypeType.CurrencyRateType.MetaData }{@code >}
     */
    public JAXBElement<CurrencyRateTypeType.CurrencyRateType.MetaData> getMetaData() {
      return metaData;
    }

    /**
     * Sets the value of the metaData property.
     *
     * @param value allowed object is {@link JAXBElement }{@code <}{@link
     *     CurrencyRateTypeType.CurrencyRateType.MetaData }{@code >}
     */
    public void setMetaData(JAXBElement<CurrencyRateTypeType.CurrencyRateType.MetaData> value) {
      this.metaData = ((JAXBElement<CurrencyRateTypeType.CurrencyRateType.MetaData>) value);
    }

    /**
     * Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="updatedBy" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="updatedOn" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}dateTime">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="createdBy" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="createdOn" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}dateTime">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(
        name = "",
        propOrder = {"updatedBy", "updatedOn", "createdBy", "createdOn"})
    public static class MetaData {

      @XmlElementRef(name = "updatedBy", type = JAXBElement.class)
      protected JAXBElement<String> updatedBy;

      @XmlElementRef(name = "updatedOn", type = JAXBElement.class)
      protected JAXBElement<XMLGregorianCalendar> updatedOn;

      @XmlElementRef(name = "createdBy", type = JAXBElement.class)
      protected JAXBElement<String> createdBy;

      @XmlElementRef(name = "createdOn", type = JAXBElement.class)
      protected JAXBElement<XMLGregorianCalendar> createdOn;

      /**
       * Gets the value of the updatedBy property.
       *
       * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
       */
      public JAXBElement<String> getUpdatedBy() {
        return updatedBy;
      }

      /**
       * Sets the value of the updatedBy property.
       *
       * @param value allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
       */
      public void setUpdatedBy(JAXBElement<String> value) {
        this.updatedBy = ((JAXBElement<String>) value);
      }

      /**
       * Gets the value of the updatedOn property.
       *
       * @return possible object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code
       *     >}
       */
      public JAXBElement<XMLGregorianCalendar> getUpdatedOn() {
        return updatedOn;
      }

      /**
       * Sets the value of the updatedOn property.
       *
       * @param value allowed object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar
       *     }{@code >}
       */
      public void setUpdatedOn(JAXBElement<XMLGregorianCalendar> value) {
        this.updatedOn = ((JAXBElement<XMLGregorianCalendar>) value);
      }

      /**
       * Gets the value of the createdBy property.
       *
       * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
       */
      public JAXBElement<String> getCreatedBy() {
        return createdBy;
      }

      /**
       * Sets the value of the createdBy property.
       *
       * @param value allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
       */
      public void setCreatedBy(JAXBElement<String> value) {
        this.createdBy = ((JAXBElement<String>) value);
      }

      /**
       * Gets the value of the createdOn property.
       *
       * @return possible object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code
       *     >}
       */
      public JAXBElement<XMLGregorianCalendar> getCreatedOn() {
        return createdOn;
      }

      /**
       * Sets the value of the createdOn property.
       *
       * @param value allowed object is {@link JAXBElement }{@code <}{@link XMLGregorianCalendar
       *     }{@code >}
       */
      public void setCreatedOn(JAXBElement<XMLGregorianCalendar> value) {
        this.createdOn = ((JAXBElement<XMLGregorianCalendar>) value);
      }
    }
  }
}
