//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-558
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.11.17 at 04:20:50 PM EST
//

@javax.xml.bind.annotation.XmlSchema(
    namespace =
        "http://services.kuehne-nagel.com/xsd/MasterData/FICurrencyRate/CurrencyRateType/V1")
package com.blumeglobal.currencyexchange.wsdl;
