//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-558
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.11.17 at 04:20:50 PM EST
//

package com.blumeglobal.currencyexchange.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for Security complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Security">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UsernameToken" type="{http://schemas.xmlsoap.org/ws/2002/04/secext}UsernameToken"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "Security",
    namespace = "http://schemas.xmlsoap.org/ws/2002/04/secext",
    propOrder = {"usernameToken"})
public class Security {

  @XmlElement(name = "UsernameToken", required = true)
  protected UsernameToken usernameToken;

  /**
   * Gets the value of the usernameToken property.
   *
   * @return possible object is {@link UsernameToken }
   */
  public UsernameToken getUsernameToken() {
    return usernameToken;
  }

  /**
   * Sets the value of the usernameToken property.
   *
   * @param value allowed object is {@link UsernameToken }
   */
  public void setUsernameToken(UsernameToken value) {
    this.usernameToken = value;
  }
}
