//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-558
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.11.17 at 04:20:50 PM EST
//

package com.blumeglobal.currencyexchange.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for select_CurrencyRateTypeRequestType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="select_CurrencyRateTypeRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="predicate" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="pagination" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="previousPageLastRecordPredicate" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="pageSize" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                         &lt;minInclusive value="1"/>
 *                         &lt;maxInclusive value="1000"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "select_CurrencyRateTypeRequestType",
    propOrder = {"predicate", "pagination"})
public class SelectCurrencyRateTypeRequestType {

  protected String predicate;
  protected SelectCurrencyRateTypeRequestType.Pagination pagination;

  /**
   * Gets the value of the predicate property.
   *
   * @return possible object is {@link String }
   */
  public String getPredicate() {
    return predicate;
  }

  /**
   * Sets the value of the predicate property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPredicate(String value) {
    this.predicate = value;
  }

  /**
   * Gets the value of the pagination property.
   *
   * @return possible object is {@link SelectCurrencyRateTypeRequestType.Pagination }
   */
  public SelectCurrencyRateTypeRequestType.Pagination getPagination() {
    return pagination;
  }

  /**
   * Sets the value of the pagination property.
   *
   * @param value allowed object is {@link SelectCurrencyRateTypeRequestType.Pagination }
   */
  public void setPagination(SelectCurrencyRateTypeRequestType.Pagination value) {
    this.pagination = value;
  }

  /**
   * Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="previousPageLastRecordPredicate" minOccurs="0">
   *           &lt;simpleType>
   *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
   *             &lt;/restriction>
   *           &lt;/simpleType>
   *         &lt;/element>
   *         &lt;element name="pageSize" minOccurs="0">
   *           &lt;simpleType>
   *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
   *               &lt;minInclusive value="1"/>
   *               &lt;maxInclusive value="1000"/>
   *             &lt;/restriction>
   *           &lt;/simpleType>
   *         &lt;/element>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(
      name = "",
      propOrder = {"previousPageLastRecordPredicate", "pageSize"})
  public static class Pagination {

    protected String previousPageLastRecordPredicate;
    protected Integer pageSize;

    /**
     * Gets the value of the previousPageLastRecordPredicate property.
     *
     * @return possible object is {@link String }
     */
    public String getPreviousPageLastRecordPredicate() {
      return previousPageLastRecordPredicate;
    }

    /**
     * Sets the value of the previousPageLastRecordPredicate property.
     *
     * @param value allowed object is {@link String }
     */
    public void setPreviousPageLastRecordPredicate(String value) {
      this.previousPageLastRecordPredicate = value;
    }

    /**
     * Gets the value of the pageSize property.
     *
     * @return possible object is {@link Integer }
     */
    public Integer getPageSize() {
      return pageSize;
    }

    /**
     * Sets the value of the pageSize property.
     *
     * @param value allowed object is {@link Integer }
     */
    public void setPageSize(Integer value) {
      this.pageSize = value;
    }
  }
}
