//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-558
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.11.17 at 04:20:50 PM EST
//

package com.blumeglobal.currencyexchange.wsdl;

import javax.xml.bind.annotation.*;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TransactionId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"transactionId"})
@XmlRootElement(name = "Transaction", namespace = "http://mdm-next.int.kn/xsd/transaction/v01")
public class Transaction {

  @XmlElement(
      name = "TransactionId",
      namespace = "http://mdm-next.int.kn/xsd/transaction/v01",
      required = true)
  protected String transactionId;

  /**
   * Gets the value of the transactionId property.
   *
   * @return possible object is {@link String }
   */
  public String getTransactionId() {
    return transactionId;
  }

  /**
   * Sets the value of the transactionId property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTransactionId(String value) {
    this.transactionId = value;
  }
}
