//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-558
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.11.17 at 04:20:50 PM EST
//

package com.blumeglobal.currencyexchange.wsdl;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;

/**
 * Attributes catalog. Catalog for user defined attributes.
 *
 * <p>Java class for UDACatalog complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="UDACatalog">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}Name"/>
 *         &lt;element name="type">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="xs:string"/>
 *               &lt;enumeration value="xs:boolean"/>
 *               &lt;enumeration value="xs:int"/>
 *               &lt;enumeration value="xs:decimal"/>
 *               &lt;enumeration value="xs:dateTime"/>
 *               &lt;enumeration value="xs:date"/>
 *               &lt;enumeration value="xs:time"/>
 *               &lt;enumeration value="xs:Name"/>
 *               &lt;enumeration value="xs:anyURI"/>
 *               &lt;enumeration value="osd:text"/>
 *               &lt;enumeration value="osd:html"/>
 *               &lt;enumeration value="osd:email"/>
 *               &lt;enumeration value="osd:password"/>
 *               &lt;enumeration value="osd:locale"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="documentation">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="localizedDocumentations" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="locale" type="{urn:ebx-schemas:common_1.0}locale"/>
 *                             &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="description" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="99999"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "UDACatalog",
    namespace = "urn:ebx-schemas:common_1.0",
    propOrder = {"name", "type", "documentation"})
public class UDACatalog {

  @XmlElement(required = true)
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  @XmlSchemaType(name = "Name")
  protected String name;

  @XmlElement(required = true)
  protected String type;

  @XmlElement(required = true)
  protected UDACatalog.Documentation documentation;

  /**
   * Gets the value of the name property.
   *
   * @return possible object is {@link String }
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   *
   * @param value allowed object is {@link String }
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the type property.
   *
   * @return possible object is {@link String }
   */
  public String getType() {
    return type;
  }

  /**
   * Sets the value of the type property.
   *
   * @param value allowed object is {@link String }
   */
  public void setType(String value) {
    this.type = value;
  }

  /**
   * Gets the value of the documentation property.
   *
   * @return possible object is {@link UDACatalog.Documentation }
   */
  public UDACatalog.Documentation getDocumentation() {
    return documentation;
  }

  /**
   * Sets the value of the documentation property.
   *
   * @param value allowed object is {@link UDACatalog.Documentation }
   */
  public void setDocumentation(UDACatalog.Documentation value) {
    this.documentation = value;
  }

  /**
   * Label and description
   *
   * <p>Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="localizedDocumentations" maxOccurs="unbounded" minOccurs="0">
   *           &lt;complexType>
   *             &lt;complexContent>
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                 &lt;sequence>
   *                   &lt;element name="locale" type="{urn:ebx-schemas:common_1.0}locale"/>
   *                   &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
   *                   &lt;element name="description" minOccurs="0">
   *                     &lt;simpleType>
   *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
   *                         &lt;maxLength value="99999"/>
   *                       &lt;/restriction>
   *                     &lt;/simpleType>
   *                   &lt;/element>
   *                 &lt;/sequence>
   *               &lt;/restriction>
   *             &lt;/complexContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(
      name = "",
      propOrder = {"localizedDocumentations"})
  public static class Documentation {

    protected List<UDACatalog.Documentation.LocalizedDocumentations> localizedDocumentations;

    /**
     * Gets the value of the localizedDocumentations property.
     *
     * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the localizedDocumentations property.
     *
     * <p>For example, to add a new item, do as follows:
     *
     * <pre>
     *    getLocalizedDocumentations().add(newItem);
     * </pre>
     *
     * <p>Objects of the following type(s) are allowed in the list {@link
     * UDACatalog.Documentation.LocalizedDocumentations }
     */
    public List<UDACatalog.Documentation.LocalizedDocumentations> getLocalizedDocumentations() {
      if (localizedDocumentations == null) {
        localizedDocumentations = new ArrayList<UDACatalog.Documentation.LocalizedDocumentations>();
      }
      return this.localizedDocumentations;
    }

    /**
     * Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="locale" type="{urn:ebx-schemas:common_1.0}locale"/>
     *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="description" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="99999"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(
        name = "",
        propOrder = {"locale", "label", "description"})
    public static class LocalizedDocumentations {

      @XmlElement(required = true)
      protected Locale locale;

      protected String label;
      protected String description;

      /**
       * Gets the value of the locale property.
       *
       * @return possible object is {@link Locale }
       */
      public Locale getLocale() {
        return locale;
      }

      /**
       * Sets the value of the locale property.
       *
       * @param value allowed object is {@link Locale }
       */
      public void setLocale(Locale value) {
        this.locale = value;
      }

      /**
       * Gets the value of the label property.
       *
       * @return possible object is {@link String }
       */
      public String getLabel() {
        return label;
      }

      /**
       * Sets the value of the label property.
       *
       * @param value allowed object is {@link String }
       */
      public void setLabel(String value) {
        this.label = value;
      }

      /**
       * Gets the value of the description property.
       *
       * @return possible object is {@link String }
       */
      public String getDescription() {
        return description;
      }

      /**
       * Sets the value of the description property.
       *
       * @param value allowed object is {@link String }
       */
      public void setDescription(String value) {
        this.description = value;
      }
    }
  }
}
